CarShop/CarShop/CarShopWebSite/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using CarShopWebSite.Areas.HelpPage.ModelDescriptions;

namespace CarShopWebSite.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

CarShop/CarShop/CarShopWebSite/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using CarShopWebSite.Areas.HelpPage.ModelDescriptions;
using CarShopWebSite.Areas.HelpPage.Models;

namespace CarShopWebSite.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

CarShop/CarShop/CarShopWebSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;
using VendorWcfService;

namespace CarShopWebSite.Controllers
{
    public class HomeController : Controller
    {
        CarsDAL DAL = new CarsDAL();
        public ActionResult Index()
        {
            List<string> vendors = DAL.SelectVendors();
            if (vendors.Count != 0)
            {
                List<string> Models = DAL.SelectModels(vendors[0]);
                ViewBag.Vendors = vendors;
            }
            
            return View();
        }
        [HttpGet]
        public JsonResult SelectModles(string vendorname)
        {
                List<string> Models = DAL.SelectModels(vendorname);

                return Json(new { Models }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ModelInfo(string model)
        {
            List<string> Models = DAL.SelectCarInfo(model);

            return Json(new { Models }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult BuyCar(string model)
        {
            DAL.BuyCar(model);
            return null;
        }


        [HttpGet]
        public ActionResult MakeOrder(string model, string vendorName)
        {
            string result;
            using (ChannelFactory<IVendorService> scf = new ChannelFactory<IVendorService>(new BasicHttpBinding(), DAL.SelectVendorServiceUrl(vendorName)))
            {
                IVendorService channel = scf.CreateChannel();
                result = channel.MakeOrder(model);
            }

            return Content(result);
        }
    }
}

CarShop/CarShop/CarShopWebSite/Controllers/VendorsController.cs
using CarShopWebSite.Hubs;
using Microsoft.AspNet.SignalR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace CarShopWebSite.Controllers
{
    public class VendorsController : ApiController
    {
        CarsDAL Dal = new CarsDAL();
        IHubContext hubContext = GlobalHost.ConnectionManager.GetHubContext<CarShopHub>();
        // GET api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        public string GetUrl([FromUri] string VendorName,[FromUri] string ServiceUrl)
        {
            bool existvendor = Dal.SetVendor(VendorName, ServiceUrl);
            if(!existvendor)
            {
                hubContext.Clients.All.AddVendor(VendorName);
            }
            return System.Configuration.ConfigurationSettings.AppSettings["ServiceUrl"];
        }

        // DELETE api/values/5
        public void Delete(string id)
        {
            Dal.DeleteVendor(id);
            hubContext.Clients.All.DeleteVendor(id);
        }
    }
}

CarShop/CarShop/CarShopWebSite/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CarShop</title>

    <script src="~/Scripts/jquery-2.1.4.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js" type="text/javascript"></script>
    <script src="~/signalr/hubs" type="text/javascript"></script>
    <script type="text/javascript">
    $(document).ready(function () {

        var carShopHub = $.connection.carShopHub;
        carShopHub.client.AddCar = function (vendor, model) {
            var myElem = document.getElementById(vendor + "-models");
            if (myElem != null)
            {
                $('#' + vendor + "-models").append('<p id="' + model + '" style="text-decoration:underline; float:left; cursor:pointer; margin-left:10px; font-size:16px;" onclick="SelectCarInfo(this)">car model: ' + model + '</p>');
            }

        };

        carShopHub.client.DeleteCar = function (vendor, model) {
            var myElem = document.getElementById(vendor + "-models");
            if (myElem != null) {
                document.getElementById(model).remove();
            }
        };

        carShopHub.client.AddVendor = function (vendor) {
            $('#vendors').append(' <div id="' + vendor + '" style="margin-top:10px;" onclick="SelectVendorCars(this)"><p style="text-decoration:underline; cursor:pointer;">' + vendor + '</p></div>');
        };

        carShopHub.client.DeleteVendor = function (vendor) {
            document.getElementById(vendor).remove();
            document.getElementById(vendor+"-models").remove();
        };

        carShopHub.client.BuyCar = function (model) {
            document.getElementById(model+"-state").textContent = "Sold";
        };

        $.connection.hub.start();
    });
    ////////////
    function SelectVendorCars(vendor) {
        var vendorName = vendor.id;
        document.getElementById('VendorName').value = vendorName;
        $('#ModelInfo').empty();
        $.ajax({
            url: "@(Url.Action("SelectModles", "Home"))",
            type: "GET",
            cache: false,
            async: true,
            data: { vendorname: vendorName },
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                $('#Vendors-cars').empty();
                var list = result;
                $.each(list, function (index, item) {
                    for (var i = 0; i < item.length; i++) {
                        var myElem = document.getElementById(vendorName + "-models");
                        if (myElem == null) {
                            $('#Vendors-cars').append('<div id="' + vendorName + "-models" + '"><p id="' + item[i] + '" style="text-decoration:underline; cursor:pointer; float:left; margin-left:10px; font-size:16px;" onclick="SelectCarInfo(this)">car model: ' + item[i] + '</p></div>');
                        }
                        else {
                            $('#' + vendorName + "-models").append('<p id="' + item[i] + '" style="text-decoration:underline; float:left; cursor:pointer; margin-left:10px; font-size:16px;" onclick="SelectCarInfo(this)">car model: ' + item[i] + '</p>');
                        }
                    }
                });
            }
        });
    }



    function SelectCarInfo(model) {
        var Model = model.id;
        document.getElementById('CarModel').value = model.id;
        $.ajax({
            url: "@(Url.Action("ModelInfo", "Home"))",
            type: "GET",
            cache: false,
            async: true,
            data: { model: Model },
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                $('#ModelInfo').empty();
                var list = result;
                $.each(list, function (index, item) {
                    $('#ModelInfo').append('<p id="' + Model + '-color" >Color: ' + item[0] + '</p>');
                    $('#ModelInfo').append('<p id="' + Model + '-price">Price: ' + item[1] + '</p>');
                    $('#ModelInfo').append('<p id="' + Model + '-state">State: ' + item[2] + '</p>');
                    if (item[2] == "Available") {
                        $('#ModelInfo').append('<input id="btn" type="button" value="Buy Car" onclick="BuyCar()"/>')
                    }
                    $('#ModelInfo').append('<input id="btn" type="button" value="Ordered Car" onclick="MakeOrder()"/>')
                });
            }
        });
    }


    function BuyCar() {
        var model = $('#CarModel').val();
        $.ajax({
            url: "@(Url.Action("BuyCar", "Home"))",
            type: "GET",
            cache: false,
            async: true,
            data: { model: model },
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
            }
        });
        document.getElementById('btn').remove();
        $('#ModelInfo').append('<p>You buy a car</p>');
    }

    function MakeOrder() {
        var model = $('#CarModel').val();
        var vendor = $('#VendorName').val();
        $.ajax({
            url: "@(Url.Action("MakeOrder", "Home"))",
            type: "GET",
            cache: false,
            async: true,
            data: { model: model, vendorName: vendor },
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                $('#d').append('<p>lol+' + result + '</p>')
            }
        });
        $('#ModelInfo').append('<p>You made order</p>');
    }



    </script>
</head>
<body style="background-color:#F0F8FF;text-align:center; width:100%; border:0px; margin:0; padding:0;">
    <div style="width:100%; background-color:#789bb0; height:50px; border:0px; margin:0; padding-top:0;"><h3 style="margin:0;padding-top:10px;">Car Shop</h3></div>
    <center>
        
        <div style="width:800px; margin-top:10px; height:auto; border:1px solid #789bb0; border-radius:10px; min-height:100px; background-color:#8fb3c8;">
            <div id="vendors" style="width:200px; min-height:100%; float:left;">
                <div style="background-color:#789bb0; width:100%; height:auto; margin-top:0; padding-top:0; border-top-left-radius:10px; height:40px; text-align:center;"><p style="font-size:20px; margin:0;padding-top:5px;">Vendors</p></div>

                @{
                    if (ViewBag.Vendors != null)
                    {
                        for (int i = 0; i < ViewBag.Vendors.Count; i++)
                        {
                            <div id="@ViewBag.Vendors[i]" style="margin-top:10px;" onclick="SelectVendorCars(this)"><p style="text-decoration:underline;cursor:pointer;">@ViewBag.Vendors[i]</p></div>
                        }
                    }
                }
            </div>
            <div style="width:600px; height:100%; float:right;  min-height:100%; background-color:#F0F8FF; border-bottom-right-radius:10px;border-top-right-radius:10px;">
                <div style="background-color:#789bb0; width:100%; height:auto; margin-top:0; padding-top:0; border-top-right-radius:10px; height:40px; text-align:center;"><p style="font-size:20px; margin:0;padding-top:5px;">Models</p></div>

                <div id="Vendors-cars" style="width:100%; height:100%; border-bottom:1px solid #789bb0; min-height:50px;">
                </div>
                <input type="text" id="VendorName" style="visibility:hidden; display:none;" />
                <input type="text" id="CarModel" style="visibility:hidden; display:none;" />
                <div id="ModelInfo" style="width:100%; height:100%; border-bottom-right-radius:10px;">
                </div>
            </div>
            <p style="clear:both;height:0; margin:0; padding:0;"></p>
        </div>
</center>
</body>
</html>

CarShop/CarShop/CarShopWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">ASP.NET Web API</a></p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>